#Exercise 1:Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.


In [1]:
import numpy as np

# Create a NumPy array containing numbers from 1 to 10
array = np.arange(1, 11)

# Reshape the array to a 2x5 matrix
reshaped_array = array.reshape(2, 5)

# Display the original array and the reshaped array
print("Original Array:")
print(array)
print("\nReshaped 2x5 Matrix:")
print(reshaped_array)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped 2x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#Exercise 2:Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.


In [ ]:
import numpy as np

# Create a NumPy array containing numbers from 1 to 20
array = np.arange(1, 21)

# Extract elements between the 5th and 15th index
# Note: Python uses 0-based indexing, so the 5th index is 6th element, and the 15th index is 16th element
extracted_elements = array[5:15]

# Display the original array and the extracted elements
print("Original Array:")
print(array)
print("\nExtracted Elements (5th to 15th index):")
print(extracted_elements)

#Exercise 3: Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.


In [2]:
import pandas as pd

# Create a Pandas series with the given data
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)

# Add a new item to the series
series['pears'] = 4

# Display the series
print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


#Exercise 4: Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [3]:
import pandas as pd

# Create a dictionary with the data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'age': [25, 30, 35, 40, 22, 28, 33, 26, 29, 31],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      name  age gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M
3    David   40      M
4      Eva   22      F
5    Frank   28      M
6    Grace   33      F
7   Hannah   26      F
8      Ivy   29      F
9     Jack   31      M


#Exercise 5: Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.


In [ ]:
import pandas as pd

# Create a dictionary with the data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'age': [25, 30, 35, 40, 22, 28, 33, 26, 29, 31],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Add a new column called occupation
occupations = ['Programmer', 'Manager', 'Analyst'] * (len(df) // 3) + ['Programmer'] * (len(df) % 3)
df['occupation'] = occupations

# Display the DataFrame
print(df)

#Exercise 6: Select the rows of the dataframe where the age is greater than or equal to 30.


In [ ]:
import pandas as pd

# Create a dictionary with the data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'age': [25, 30, 35, 40, 22, 28, 33, 26, 29, 31],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Select rows where age is greater than or equal to 30
filtered_df = df[df['age'] >= 30]

# Display the filtered DataFrame
print(filtered_df)

#Exercise 7: Convert this dataframe to a csv file and read that csv file, finally display the contents.


In [4]:
import pandas as pd

# Create a dictionary with the data
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'age': [25, 30, 35, 40, 22, 28, 33, 26, 29, 31],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Convert the DataFrame to a CSV file
csv_file = "dataframe.csv"
df.to_csv(csv_file, index=False)

# Read the CSV file
df_from_csv = pd.read_csv(csv_file)

# Display the contents of the CSV file
print(df_from_csv)

      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   30      M     Manager
2  Charlie   35      M     Analyst
3    David   40      M  Programmer
4      Eva   22      F     Manager
5    Frank   28      M     Analyst
6    Grace   33      F  Programmer
7   Hannah   26      F     Manager
8      Ivy   29      F     Analyst
9     Jack   31      M  Programmer
